# Generated by Django 3.1.2 on 2020-10-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='limit',
        ),
        migrations.AddField(
            model_name='event',
            name='limit_ticket',
            field=models.IntegerField(default=0),
        ),
    ]
