# Generated by Django 3.1.2 on 2020-10-11 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201009_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='age_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=None)),
                ('public', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AlterField(
            model_name='event',
            name='limit_ticket',
            field=models.IntegerField(default=None),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('age_rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.age_rating')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event')),
            ],
        ),
    ]
