# Generated by Django 3.1.2 on 2020-10-11 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201010_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='age_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.age_rating'),
        ),
    ]
