# Generated by Django 3.1.2 on 2020-10-11 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20201010_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='age_rating',
        ),
        migrations.AddField(
            model_name='event',
            name='age_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.age_rating'),
        ),
    ]
